project:
  type: website

  render:
    - "*.qmd"
    - "journey/**/*.qmd"
    - "projects/**/*.qmd"
    - "reviews/**/*.qmd"
    - "hobbies/**/*.qmd"
    - "!research/**"

  resources:
    - robots.txt
    - images/
    - assets/

lang: en

filters:
  - _includes/git-modified.lua

execute:
  freeze: auto

website:
  title: "datapiquing"
  description: "A personal learning journal documenting my hobbies, projects and discoveries."
  site-url: https://datapiquing.com

  navbar:
    left:
      - text: Now
        href: now.qmd

      - text: Hobbies
        menu:
          - text: Toolsmithing
            href: hobbies/toolsmithing/index.qmd
          - text: Robotics
            href: hobbies/robotics/index.qmd
          - text: Photography
            href: hobbies/photography/index.qmd
          - text: Outdoor Pursuits
            href: hobbies/outdoor/index.qmd

      - text: Projects
        href: projects/index.qmd

      - text: Journey
        href: journey/index.qmd

      - text: Reviews
        href: reviews/index.qmd

      - text: About
        href: about.qmd

    right:
      - icon: github
        href: https://github.com/datapiquing

  page-footer:
    center: "© 2026 Garry Sykes"

  open-graph: true
  twitter-card: true

format:
  html:
    theme:
      - cosmo
      - styles.scss

    toc: true
    code-copy: true
    code-overflow: wrap

    date-modified: last-modified
    date-format: medium

    include-after-body: _includes/reorder-title-meta.html
